//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "authors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::serie_authors::Entity")]
    SerieAuthors,
}

impl Related<super::serie_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieAuthors.def()
    }
}

impl Related<super::series::Entity> for Entity {
    fn to() -> RelationDef {
        super::serie_authors::Relation::Series.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::serie_authors::Relation::Authors.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
