//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod artists;
pub mod auth_state;
pub mod authors;
pub mod genres;
pub mod sea_orm_active_enums;
pub mod serie_artists;
pub mod serie_authors;
pub mod serie_genres;
pub mod serie_sources;
pub mod serie_status;
pub mod serie_synopsis;
pub mod serie_titles;
pub mod serie_types;
pub mod series;
pub mod sources;
pub mod statuses;
pub mod user;
pub mod user_preference;
pub mod user_session;
