//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql :: SimpleObject,
)]
#[sea_orm(table_name = "series")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub cover_url: String,
    pub serie_type_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::serie_artists::Entity")]
    SerieArtists,
    #[sea_orm(has_many = "super::serie_authors::Entity")]
    SerieAuthors,
    #[sea_orm(has_many = "super::serie_genres::Entity")]
    SerieGenres,
    #[sea_orm(has_many = "super::serie_sources::Entity")]
    SerieSources,
    #[sea_orm(has_many = "super::serie_status::Entity")]
    SerieStatus,
    #[sea_orm(has_many = "super::serie_synopsis::Entity")]
    SerieSynopsis,
    #[sea_orm(has_many = "super::serie_titles::Entity")]
    SerieTitles,
    #[sea_orm(
        belongs_to = "super::serie_types::Entity",
        from = "Column::SerieTypeId",
        to = "super::serie_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SerieTypes,
}

impl Related<super::serie_artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieArtists.def()
    }
}

impl Related<super::serie_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieAuthors.def()
    }
}

impl Related<super::serie_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieGenres.def()
    }
}

impl Related<super::serie_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieSources.def()
    }
}

impl Related<super::serie_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieStatus.def()
    }
}

impl Related<super::serie_synopsis::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieSynopsis.def()
    }
}

impl Related<super::serie_titles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieTitles.def()
    }
}

impl Related<super::serie_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieTypes.def()
    }
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        super::serie_artists::Relation::Artists.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::serie_artists::Relation::Series.def().rev())
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        super::serie_authors::Relation::Authors.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::serie_authors::Relation::Series.def().rev())
    }
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::serie_genres::Relation::Genres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::serie_genres::Relation::Series.def().rev())
    }
}

impl Related<super::sources::Entity> for Entity {
    fn to() -> RelationDef {
        super::serie_sources::Relation::Sources.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::serie_sources::Relation::Series.def().rev())
    }
}

impl Related<super::statuses::Entity> for Entity {
    fn to() -> RelationDef {
        super::serie_status::Relation::Statuses.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::serie_status::Relation::Series.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
