//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "serie_status")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serie_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub status_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::series::Entity",
        from = "Column::SerieId",
        to = "super::series::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Series,
    #[sea_orm(
        belongs_to = "super::statuses::Entity",
        from = "Column::StatusId",
        to = "super::statuses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Statuses,
}

impl Related<super::series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Series.def()
    }
}

impl Related<super::statuses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Statuses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
