//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql :: SimpleObject,
)]
#[sea_orm(table_name = "statuses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::serie_status::Entity")]
    SerieStatus,
}

impl Related<super::serie_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SerieStatus.def()
    }
}

impl Related<super::series::Entity> for Entity {
    fn to() -> RelationDef {
        super::serie_status::Relation::Series.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::serie_status::Relation::Statuses.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
