name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [created]

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "docker/sources.Dockerfile"
          push: true
          tags: ghcr.io/azsiaz/dokusho-sources:latest
          labels: org.opencontainers.image.source=https://github.com/azsiaz/dokusho-backends
          platforms: linux/amd64,linux/arm64

      - name: Push versioned tag (if release)
        if: github.event_name == 'release'
        run: |
          docker tag ghcr.io/azsiaz/dokusho-sources:latest ghcr.io/azsiaz/dokusho-sources:${{ github.event.release.tag_name }}
          docker push ghcr.io/azsiaz/dokusho-sources:${{ github.event.release.tag_name }}
